apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: dev
  namespace: kargo-helm
  annotations:
    kargo.akuity.io/color: green
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: guestbook
    sources:
      direct: true
  - origin:
      kind: Warehouse
      name: features
    sources:
      direct: true
  promotionTemplate:
    spec:
      steps:
      - task:
          name: promote
        vars:
        - name: envPath
          value: env/dev
        - name: argocdApp
          value: kargo-helm-dev
        - name: argocdSecondApp
          value: some-config-dev

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: test
  namespace: kargo-helm
  annotations:
    kargo.akuity.io/color: yellow
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: guestbook
    sources:
      stages:
        - dev
  - origin:
      kind: Warehouse
      name: features
    sources:
      stages:
        - dev
  promotionTemplate:
    spec:
      steps:
      - task:
          name: promote
        vars:
        - name: envPath
          value: env/test
        - name: argocdApp
          value: kargo-helm-test
        - name: argocdSecondApp
          value: some-config-test

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod
  namespace: kargo-helm
  annotations:
    kargo.akuity.io/color: red
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: guestbook
    sources:
      stages:
        - test
  - origin:
      kind: Warehouse
      name: features
    sources:
      stages:
        - test
  promotionTemplate:
    spec:
      steps:
      - task:
          name: promote
        vars:
        - name: envPath
          value: env/prod
        - name: argocdApp
          value: kargo-helm-prod
        - name: argocdSecondApp
          value: some-config-prod
