apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: some-config
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/zeraye/kargo-helm.git
      revision: HEAD
      directories:
      - path: env/*
  template:
    metadata:
      name: some-config-{{path.basename}}
      annotations:
        kargo.akuity.io/authorized-stage: kargo-helm:{{path.basename}}
    spec:
      destination:
        namespace: kargo-helm-{{path.basename}}
        name: in-cluster
      project: kargo-helm
      source:
        path: base/some-config
        repoURL: https://github.com/zeraye/kargo-helm.git
